spring.application.name=ERP SCM

server.port=9095
spring.application.version=@project.version@
# DB Connection Configuration
keycloak.url=http://172.17.17.254:8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.url}/realms/aesl
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs


spring.datasource.url=jdbc:mysql://172.17.17.254:3306/erp_scm?useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8
spring.datasource.username=root
spring.datasource.password=password


spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hikari Configuration
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.maximumPoolSize=15
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=SpringBootJPAHikariCP
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000

logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
logging.file.name=./log/app-log.log
spring.output.ansi.enabled=ALWAYS

#file config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
server.tomcat.max-http-form-post-size=10485760
upload.dir=./uploads
#######################
######Email Config#####

mail.address  = http://172.17.17.53/comsys/api
mail.loginUrl = /auth/login
mail.sendUrl  = /mail/send-email
mail.user=admin
mail.password=admin123

# mail reset link and demand detail page link from fontend of scm
mail.resetPassLink = http://172.17.18.47:4201/fe/auth/set-password/

scm.frontend.demandDetailLink = http://172.17.18.50:4201/fe/editor/demand/detail/

########################
####CPS VMS CONFIG #####
cps.erpIpAddress        = http://172.17.18.79:9095/api/v1
cps.orgCode             = aesl_v3
cps.host                = http://172.17.18.79:9092/api/v1
cps.tenderEndpoint      = /tenders
cps.vendorCountEndpoint = /vendors/count/{subCatCode}
cps.vendorListEndpoint  = /vendors/list
cps.counterOfferEndpoint =/offers/counter-offer/{rfqNo}/receive
cps.lockOfferEndpoint   = /offers/{remoteOfferId}/lock/{vendorId}
cps.declineOfferEndpoint   = /offers/{remoteOfferId}/decline/{vendorId}
cps.awardedOfferEndpoint   = /offers/{remoteOfferId}/awarded/{vendorId}
cps.sentPoEndpoint      = /po
cps.poReceiveEndpoint   = /po-send/{id}/received-grn
cps.poRejectEndpoint    = /po-send/{id}/declined-grn
cps.poQcFailEndpoint    = /po-send/{id}/decline-qc
cps.poQcPassEndpoint    = /po-send/{id}/receive-qc
cps.orgRegisterEndpoint = /organizations/register
cps.itemFetchEndpoint   = /items/sub-category/{subCatCode}
cps.pendingItemReqEndpoint = /pending-item-requests
cps.itemCategoriesEndpoint = /item-categories
cps.itemsEndpoint        = /items

acl.apiEndpoint = http://172.17.18.79:9093/api/v1

app.hr.basePath = http://172.17.18.64:8002/api/method
app.acc.basePath = http://172.17.18.118:9096/api/v1

app.hr.create.warehouse = ${app.hr.basePath}/custom_erp_app.warehouse_api.create
app.hr.update.warehouse = ${app.hr.basePath}/custom_erp_app.warehouse_api.update
app.hr.delete.warehouse = ${app.hr.basePath}/custom_erp_app.warehouse_api.delete
#app.hr.ledger.item.create = ${app.hr.basePath}/custom_erp_app.chart_of_account_api.create_item
app.acc.ledger.item.create = ${app.acc.basePath}/item-ledger/create
app.hr.purchase_receipt.create = ${app.hr.basePath}/custom_erp_app.purchase_receipt_api.create_purchase_receipt


#spring.sql.init.mode=always
# T H I S   L I N E    I S    E X E C U T E D    O N L Y    A T    F I R S T    D E P L O Y M E N T !!!!!!!!!!!!!!!
# spring.sql.init.data-locations=file:src/main/resources/db/data.sql

# Swagger Config
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher

###############SERVICES###################
service.hr=erpnext2
service.scm=erp-scm-api